# octocov is used for bundle size tracking only.
# Coverage reporting is handled by Codecov.
coverage:
  acceptable: 0%

codeToTestRatio:
  acceptable: 0%

testExecutionTime:
  acceptable: 0 sec

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

comment:
  enable: true
  hideFooterLink: false

summary:
  enable: true
