packages:
  - packages/*
  - apps/*

catalog:
  '@opentelemetry/api': ^1.9.0
  '@types/node': 20.19.25
  tsdown: 0.21.2
  typescript: 5.9.3
  vitest: 3.2.3
  zod: 4.2.1

sharedWorkspaceLockfile: false
