---
plan_workflow_name: Terraform Plan
update_local_path_module_caller:
  enabled: true
trivy:
  enabled: true
tflint:
  enabled: true
  fix: true

target_groups:
  - working_directory: terraform/env/dev/
    target: my-app/dev/