---
    name: Terraform Plan Dev
    
    on:
      pull_request:
        branches:
          - develop
        paths:
          - 'infrastructure/terraform/env/dev/**'
          - 'infrastructure/terraform/modules/**'
          - .github/workflows/terraform-plan-dev.yml
    
    
    concurrency:
      group: my-app
      cancel-in-progress: false
    
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    
    env:
      AQUA_CONFIG: "${{ github.workspace }}/aqua.yaml"
      TFACTION_CONFIG: "${{ github.workspace }}/infrastructure/terraform/tfaction.yaml"
    
    jobs:
      setup:
        name: Set up
        runs-on: ubuntu-latest
        timeout-minutes: 5
        defaults:
          run:
            shell: bash
        outputs:
          targets: ${{ steps.list-targets.outputs.targets }}
          modules: ${{ steps.list-targets.outputs.modules }}
        steps:
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
          - name: Install tools
            uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342
            with:
              aqua_version: v2.55.0
          - name: Get changed working directory
            uses: suzuki-shunsuke/tfaction/list-targets@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6
            id: list-targets
    
      plan:
        name: Plan (${{ matrix.target.target }})
        environment: production
        needs: setup
        if: join(fromJSON(needs.setup.outputs.targets), '') != ''
        runs-on: ubuntu-latest
        timeout-minutes: 10
        defaults:
          run:
            shell: bash
        env:
          TFACTION_TARGET: ${{ matrix.target.target }}
          TFACTION_WORKING_DIR: ${{ matrix.target.working_directory }}
          TFACTION_JOB_TYPE: ${{ matrix.target.job_type }}
          TFLINT_CONFIG_FILE: "${{ github.workspace }}/terraform/.tflint.hcl"
          TRIVY_SEVERITY: HIGH,CRITICAL
          TRIVY_SKIP_DIRS: ".terraform"
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
    
        strategy:
          fail-fast: false
          matrix:
            target: ${{ fromJSON(needs.setup.outputs.targets) }}
        steps:
          - name: Checkout
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
          
          - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
            id: app-token
            with:
              app-id: ${{ secrets.MY_APP_GITHUB_APP_ID}}
              private-key: ${{ secrets.MY_APP_GITHUB_APP_PRIVATE_KEY }}
              owner: ${{ github.repository_owner }}
    
          - name: Install tools
            uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342
            with:
              aqua_version: v2.55.0
    
          - id: google-auth
            name: Authenticate to Google Cloud
            uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
            with:
              project_id: ${{ secrets.GCP_PROJECT_ID }}
              workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
              service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    
          - name: Set up
            uses: suzuki-shunsuke/tfaction/setup@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6
            with:
              github_token: ${{ steps.app-token.outputs.token }}
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
    
          - name: Test
            uses: suzuki-shunsuke/tfaction/test@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6
            continue-on-error: true
            with:
              github_token: ${{ steps.app-token.outputs.token }}
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
    
          - name: Plan
            uses: suzuki-shunsuke/tfaction/plan@d8646dcdc60933280ab9a229bd2a8d8c6390e1b6
            with:
              github_token: ${{ steps.app-token.outputs.token }}
            env:
              GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}